"""
MASAISAI live dashboard (Streamlit).

Reframed 27 Jul 2026 from an "access console" to a utilization/compliance dashboard, after
direct feedback from a POTRAZ spectrum-management expert: the pipeline underneath (sensing ->
ML occupancy forecast -> rules veto -> logged decision) is unchanged, only what the system is
*for* changed -- see `Pitching and Presenting/04_ANTICIPATED_QUESTIONS.md` section 6c. It no
longer claims to grant third-party access; it measures utilization on one band (UHF TVWS) and
flags anomalies for POTRAZ's own review, not an autonomous verdict.

Chosen over Grafana/InfluxDB for zero extra infrastructure to stand up for a bootcamp demo --
same reasoning as the Part 5 fault-injection testbed's dashboard. Runs entirely against the
synthetic sensing data generated by sensing_sim.py plus the trained occupancy model and
constraint engine, so it works without any real SDR hardware connected.

Run: streamlit run dashboard_app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pandas as pd
import streamlit as st

from constraint_engine import decide_access, load_rules
from occupancy_model import FEATURE_COLUMNS, add_features, predict_model_proba, train_model
from sensing_sim import generate_dataset

st.set_page_config(page_title="MASAISAI -- Spectrum Utilization & Compliance Dashboard", layout="wide")

st.title("MASAISAI -- AI-Governed Spectrum Utilization & Compliance Dashboard")
st.caption(
    "One band, UHF TV white space (470-694 MHz). Simulated demo: synthetic sensing data (no "
    "real SDR hardware connected in this environment) driving the real ML utilization-forecast "
    "model and POTRAZ-rules constraint engine. The AI forecasts and flags -- it never grants "
    "access or makes a final call; every flag is a triage signal for POTRAZ's own review."
)


@st.cache_data
def load_data():
    raw = generate_dataset(n_days=14, test_period_days=4, seed=3)
    return add_features(raw)


@st.cache_resource
def get_model(train_df: pd.DataFrame):
    return train_model(train_df)


data = load_data()
train_df = data[data["split"] == "train"]
test_df = data[data["split"] == "test"].copy()
model = get_model(train_df)
rules = load_rules()

test_df["ml_probability"] = predict_model_proba(model, test_df)

band_utilization_pct = test_df["occupied"].mean() * 100

col1, col2, col3, col4 = st.columns(4)
col1.metric("Sensing nodes", test_df["node_id"].nunique())
col2.metric("Channels monitored (this band)", test_df["channel"].nunique())
col3.metric("Band-wide utilization (test period)", f"{band_utilization_pct:.1f}%")
col4.metric("Protected channels (rules layer)", len(rules.get("protected_channels", [])))

st.subheader("Band utilization over time (hour of day)")
st.caption(
    "How much of this band is actually occupied, by hour -- the visibility POTRAZ doesn't "
    "currently have from a static ZNFAP allocation table alone."
)
hourly_utilization = test_df.groupby("hour")["occupied"].mean() * 100
st.line_chart(hourly_utilization, x_label="Hour of day", y_label="Utilization %")

st.subheader("Utilization forecast by channel (ML, next sensing window)")
chart_data = test_df.pivot_table(index="channel", columns="node_id", values="ml_probability")
st.bar_chart(chart_data.mean(axis=1), y_label="Forecast occupancy probability")

st.subheader("Live spectrum snapshot (latest simulated reading per node/channel)")
latest = (
    test_df.sort_values(["day_index", "next_hour"])
    .groupby(["node_id", "channel"])
    .tail(1)
    .reset_index(drop=True)
)

decisions = [
    decide_access(row.node_id, row.channel, row.ml_probability, row.sensing_confidence, rules)
    for row in latest.itertuples()
]
latest["classification"] = ["CONFORMS" if d.granted else "FLAGGED FOR REVIEW" for d in decisions]
latest["reason"] = [d.reason for d in decisions]

display_cols = ["node_id", "channel", "rssi_dbm", "sensing_confidence", "ml_probability", "classification", "reason"]
st.dataframe(latest[display_cols].sort_values(["channel", "node_id"]), use_container_width=True)

conforms_count = (latest["classification"] == "CONFORMS").sum()
flagged_count = (latest["classification"] == "FLAGGED FOR REVIEW").sum()
st.subheader(f"This snapshot: {conforms_count} conforming / {flagged_count} flagged for review")

with st.expander("Audit log (every reading classified, fully explained)"):
    st.caption(
        "Internally the constraint engine still records its historical GRANTED/DENIED "
        "wording (unchanged, fully tested) -- read GRANTED as 'conforms to expected "
        "utilization' and DENIED as 'flagged for review' under the current framing."
    )
    st.dataframe(pd.DataFrame([d.to_dict() for d in decisions]), use_container_width=True)

with st.expander("Rules layer currently loaded (illustrative placeholder -- see data/DATASET_STATEMENT.md)"):
    st.json(rules)
