"""
MASAISAI live dashboard (Streamlit).

Chosen over Grafana/InfluxDB for zero extra infrastructure to stand up for
a bootcamp demo -- same reasoning as the Part 5 fault-injection testbed's
dashboard. Runs entirely against the synthetic sensing data generated by
sensing_sim.py plus the trained occupancy model and constraint engine, so
it works without any real SDR hardware connected.

Run: streamlit run dashboard_app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pandas as pd
import streamlit as st

from constraint_engine import decide_access, load_rules
from occupancy_model import FEATURE_COLUMNS, add_features, predict_model_proba, train_model
from sensing_sim import generate_dataset

st.set_page_config(page_title="MASAISAI -- Spectrum Access Console", layout="wide")

st.title("MASAISAI -- AI-Driven Dynamic Spectrum Access Console")
st.caption(
    "Simulated demo: synthetic sensing data (no real SDR hardware connected in this "
    "environment) driving the real ML occupancy model and POTRAZ-rules constraint engine."
)


@st.cache_data
def load_data():
    raw = generate_dataset(n_days=14, test_period_days=4, seed=3)
    return add_features(raw)


@st.cache_resource
def get_model(train_df: pd.DataFrame):
    return train_model(train_df)


data = load_data()
train_df = data[data["split"] == "train"]
test_df = data[data["split"] == "test"].copy()
model = get_model(train_df)
rules = load_rules()

test_df["ml_probability"] = predict_model_proba(model, test_df)

col1, col2, col3 = st.columns(3)
col1.metric("Sensing nodes", test_df["node_id"].nunique())
col2.metric("Channels monitored", test_df["channel"].nunique())
col3.metric("Protected channels (rules layer)", len(rules.get("protected_channels", [])))

st.subheader("Live spectrum snapshot (latest simulated reading per node/channel)")
latest = (
    test_df.sort_values(["day_index", "next_hour"])
    .groupby(["node_id", "channel"])
    .tail(1)
    .reset_index(drop=True)
)

decisions = [
    decide_access(row.node_id, row.channel, row.ml_probability, row.sensing_confidence, rules)
    for row in latest.itertuples()
]
latest["decision"] = ["GRANT" if d.granted else "DENY" for d in decisions]
latest["reason"] = [d.reason for d in decisions]

display_cols = ["node_id", "channel", "rssi_dbm", "sensing_confidence", "ml_probability", "decision", "reason"]
st.dataframe(latest[display_cols].sort_values(["channel", "node_id"]), use_container_width=True)

grant_count = (latest["decision"] == "GRANT").sum()
deny_count = (latest["decision"] == "DENY").sum()
st.subheader(f"Access decisions this snapshot: {grant_count} granted / {deny_count} denied")

st.subheader("Occupancy probability by channel (ML forecast for next window)")
chart_data = latest.pivot_table(index="channel", columns="node_id", values="ml_probability")
st.bar_chart(chart_data.mean(axis=1))

with st.expander("Audit log (every decision, fully explained)"):
    st.dataframe(pd.DataFrame([d.to_dict() for d in decisions]), use_container_width=True)

with st.expander("Rules layer currently loaded (illustrative placeholder -- see data/DATASET_STATEMENT.md)"):
    st.json(rules)
