"""
MASAISAI live dashboard (Streamlit).

Reworked 27 Jul 2026 (later the same night) from a per-node "utilization console" into a
fused, per-channel "idle-verification" console -- see `Pitching and Presenting/
04_ANTICIPATED_QUESTIONS.md` section 1. The AI's job is no longer forecasting a future window
to feed a grant/deny decision: it fuses several independently noisy, confidence-scored sensing
nodes into one robust, current-window verdict on whether a band is genuinely idle, which a
single sensor or an unweighted majority vote can't do as reliably (see occupancy_model.py's
module docstring for the full "why AI" argument, and the fusion-vs-naive-vote numbers surfaced
below). This dashboard exists to show, plainly, both how the AI reaches that verdict and the
raw sensor data it's built from.

Visual design pass 28 Jul 2026: premium dark console treatment (IBM Plex type, navy/teal
brand match with the pitch deck, bordered card layout using Streamlit 1.58's native
`border=True` on metric/container rather than fragile CSS overrides) via the ui-ux-pro-max
design skill -- functional structure unchanged from the fusion rework above, this only
changes how it looks.

Chosen over Grafana/InfluxDB for zero extra infrastructure to stand up for a bootcamp demo --
same reasoning as the Part 5 fault-injection testbed's dashboard. Runs entirely against the
synthetic sensing data generated by sensing_sim.py plus the trained fusion model and
constraint engine, so it works without any real SDR hardware connected.

Run: streamlit run dashboard_app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from constraint_engine import decide_access, load_rules
from occupancy_model import (
    ENERGY_DETECTION_THRESHOLD_DBM,
    build_fusion_frame,
    predict_model_proba,
    run_comparison,
    train_model,
)
from sensing_sim import generate_dataset

# ---------- Brand palette (matches MASAISAI_Pitch_Deck.pptx navy/teal identity) ----------
BG = "#0B1C33"
SURFACE = "#122A4D"
SURFACE_ALT = "#0F2340"
BORDER = "rgba(255,255,255,0.10)"
INK = "#F1F5F9"
INK_MUTED = "#B9C6D6"
TEAL = "#2EC4B6"
GOLD = "#F5A623"
GREEN = "#22C55E"
AMBER = "#F59E0B"
GRID = "rgba(255,255,255,0.08)"

st.set_page_config(page_title="MASAISAI -- AI Idle-Verification Console", layout="wide")

st.markdown(
    f"""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap');

    html, body, [class*="css"] {{
        font-family: 'IBM Plex Sans', system-ui, -apple-system, sans-serif;
    }}
    .stApp {{ background-color: {BG}; }}
    #MainMenu, footer, header {{ visibility: hidden; }}
    .block-container {{ padding-top: 2rem; max-width: 1320px; }}

    h1, h2, h3 {{ font-family: 'IBM Plex Sans', sans-serif; color: {INK}; letter-spacing: -0.01em; }}
    p, span, div, label {{ color: {INK}; }}

    .masaisai-badge {{
        display: inline-flex; align-items: center; gap: 0.4rem;
        font-family: 'IBM Plex Mono', monospace;
        font-size: 0.72rem; font-weight: 600; letter-spacing: 0.04em;
        color: {TEAL}; background: rgba(46,196,182,0.10);
        border: 1px solid rgba(46,196,182,0.35); border-radius: 999px;
        padding: 0.25rem 0.75rem; text-transform: uppercase; margin-bottom: 0.6rem;
    }}
    .masaisai-caption {{ color: {INK_MUTED}; font-size: 0.95rem; line-height: 1.55; max-width: 900px; }}

    .section-label {{
        color: {TEAL}; font-family: 'IBM Plex Mono', monospace;
        font-size: 0.76rem; font-weight: 600; text-transform: uppercase;
        letter-spacing: 0.08em; margin: 0 0 0.6rem 0;
    }}
    .section-desc {{ color: {INK_MUTED}; font-size: 0.88rem; margin-bottom: 0.9rem; }}

    div[data-testid="stMetric"] {{
        background: {SURFACE}; border: 1px solid {BORDER} !important; border-radius: 12px;
    }}
    div[data-testid="stMetricLabel"] {{ color: {INK_MUTED}; font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.03em; }}
    div[data-testid="stMetricValue"] {{ color: {INK}; font-family: 'IBM Plex Mono', monospace; }}
    div[data-testid="stMetricDelta"] {{ font-family: 'IBM Plex Mono', monospace; }}

    div[data-testid="stVerticalBlockBorderWrapper"] {{
        background: {SURFACE_ALT}; border-color: {BORDER} !important; border-radius: 14px;
    }}

    div[data-testid="stExpander"] {{
        background: {SURFACE}; border: 1px solid {BORDER}; border-radius: 12px;
    }}
    div[data-testid="stExpander"] summary {{ font-family: 'IBM Plex Mono', monospace; color: {INK}; }}

    div[data-testid="stDataFrame"] {{ border: 1px solid {BORDER}; border-radius: 10px; overflow: hidden; }}

    .stButton>button, div[data-baseweb="segmented-control"] {{ font-family: 'IBM Plex Sans', sans-serif; }}
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown('<div class="masaisai-badge">Simulated demo &middot; synthetic sensing data</div>', unsafe_allow_html=True)
st.title("MASAISAI — AI-Verified Spectrum Idle Console")
st.markdown(
    '<div class="masaisai-caption">One band, UHF TV white space (470&ndash;694 MHz). No real '
    "SDR hardware connected in this environment &mdash; the AI fuses several nodes' noisy "
    "readings into one verified idle/occupied verdict per channel. It never grants access or "
    "makes a final call; every flag is a triage signal for POTRAZ's own review.</div>",
    unsafe_allow_html=True,
)
st.write("")


@st.cache_data
def load_data():
    raw = generate_dataset(n_days=14, test_period_days=4, seed=3)
    fused = build_fusion_frame(raw)
    return raw, fused


@st.cache_resource
def get_model(train_df: pd.DataFrame):
    return train_model(train_df)


raw, fused = load_data()
train_df = fused[fused["split"] == "train"]
test_df = fused[fused["split"] == "test"].copy()
model = get_model(train_df)
rules = load_rules()

test_df["ml_probability"] = predict_model_proba(model, test_df)
band_utilization_pct = test_df["occupied"].mean() * 100

comparison = run_comparison(train_df, test_df)
fusion_acc = comparison["ml_score"]["accuracy"] * 100
baseline_acc = comparison["baseline_score"]["accuracy"] * 100

col1, col2, col3, col4 = st.columns(4)
col1.metric("Sensing nodes", raw["node_id"].nunique(), border=True)
col2.metric("Channels monitored (this band)", test_df["channel"].nunique(), border=True)
col3.metric("Band-wide utilization", f"{band_utilization_pct:.1f}%", border=True)
col4.metric("Protected channels (rules layer)", len(rules.get("protected_channels", [])), border=True)

st.write("")
with st.container(border=True):
    st.markdown('<div class="section-label">How the AI verifies idle</div>', unsafe_allow_html=True)
    ai_col1, ai_col2 = st.columns([3, 2], gap="large")
    with ai_col1:
        st.markdown(
            f'<div class="masaisai-caption">A single node\'s own energy-detection threshold '
            f"(RSSI &gt; {ENERGY_DETECTION_THRESHOLD_DBM:.0f} dBm, the same cutoff the sensing "
            "firmware uses) can be wrong on its own &mdash; multipath fade, transient "
            "interference, or just standing somewhere with poor signal geometry. An unweighted "
            "majority vote across nodes helps, but treats every node's vote equally regardless "
            "of how trustworthy that particular reading is. The model instead fuses each "
            "channel's mean/min/max/spread RSSI, confidence-weighted vote, and recent history "
            "into one learned, auditable verdict.</div>",
            unsafe_allow_html=True,
        )
    with ai_col2:
        sub1, sub2 = st.columns(2)
        sub1.metric("Naive-vote baseline", f"{baseline_acc:.1f}%", border=True)
        sub2.metric(
            "AI fusion model", f"{fusion_acc:.1f}%",
            delta=f"+{fusion_acc - baseline_acc:.1f} pp", border=True,
        )
        st.caption(
            f"Baseline recall {comparison['baseline_score']['recall']*100:.1f}% -- its errors "
            "are missed occupancy (the dangerous direction for incumbent protection), not "
            "false alarms."
        )

st.write("")
with st.container(border=True):
    st.markdown('<div class="section-label">Band utilization over time</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="section-desc">How much of this band is actually occupied, by hour -- '
        "the visibility POTRAZ doesn't currently have from a static ZNFAP allocation table "
        "alone.</div>",
        unsafe_allow_html=True,
    )
    hourly_utilization = (test_df.groupby("hour")["occupied"].mean() * 100).reindex(range(24), fill_value=0)
    fig = go.Figure(go.Scatter(
        x=hourly_utilization.index, y=hourly_utilization.values,
        mode="lines", line=dict(color=TEAL, width=2.5, shape="spline"),
        fill="tozeroy", fillcolor="rgba(46,196,182,0.12)",
        hovertemplate="Hour %{x}:00<br>%{y:.1f}%% utilization<extra></extra>",
    ))
    fig.update_layout(
        height=280, margin=dict(l=10, r=10, t=10, b=10),
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font=dict(color=INK_MUTED, family="IBM Plex Sans, sans-serif"),
        xaxis=dict(title="Hour of day", showgrid=False, color=INK_MUTED, linecolor=GRID, dtick=2),
        yaxis=dict(title="Utilization %", showgrid=True, gridcolor=GRID, zeroline=False, color=INK_MUTED),
    )
    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

st.write("")
with st.container(border=True):
    st.markdown('<div class="section-label">Verified idle status by channel</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="section-desc">Latest fused reading per channel, classified by the rules '
        "layer.</div>",
        unsafe_allow_html=True,
    )
    latest = (
        test_df.sort_values(["day_index", "hour"])
        .groupby("channel")
        .tail(1)
        .reset_index(drop=True)
    )

    decisions = [
        # Fail-safe gate uses the BEST contributing node's confidence, not the mean across all
        # of them -- fusion's whole point is that one reliable node is enough to trust a
        # reading even when several others are degraded; a mean would punish a channel for
        # having any poor nodes at all, discarding exactly the redundancy fusion exploits.
        decide_access("FUSED", row.channel, row.ml_probability, row.max_confidence, rules)
        for row in latest.itertuples()
    ]
    latest["classification"] = ["VERIFIED IDLE" if d.granted else "FLAGGED FOR REVIEW" for d in decisions]
    latest["reason"] = [d.reason for d in decisions]

    display_cols = [
        "channel", "day_index", "hour", "mean_rssi_dbm", "naive_vote_frac",
        "max_confidence", "ml_probability", "classification", "reason",
    ]
    table = latest[display_cols].sort_values("channel")

    def _status_style(v):
        if v == "VERIFIED IDLE":
            return f"background-color: rgba(34,197,94,0.16); color: {GREEN}; font-weight: 600;"
        return f"background-color: rgba(245,158,11,0.16); color: {AMBER}; font-weight: 600;"

    styled = table.style.map(_status_style, subset=["classification"])
    st.dataframe(
        styled,
        use_container_width=True,
        hide_index=True,
        column_config={
            "channel": "Channel",
            "day_index": "Day",
            "hour": "Hour",
            "mean_rssi_dbm": st.column_config.NumberColumn("Mean RSSI", format="%.1f dBm"),
            "naive_vote_frac": st.column_config.ProgressColumn("Naive vote", min_value=0.0, max_value=1.0, format="%.2f"),
            "max_confidence": st.column_config.ProgressColumn("Best confidence", min_value=0.0, max_value=1.0, format="%.2f"),
            "ml_probability": st.column_config.ProgressColumn("P(occupied), fused", min_value=0.0, max_value=1.0, format="%.2f"),
            "classification": "Status",
            "reason": "Reason",
        },
    )

    verified_count = int((latest["classification"] == "VERIFIED IDLE").sum())
    flagged_count = int((latest["classification"] == "FLAGGED FOR REVIEW").sum())
    snap1, snap2 = st.columns(2)
    snap1.metric("Verified idle, this snapshot", verified_count, border=True)
    snap2.metric("Flagged for review, this snapshot", flagged_count, border=True)

st.write("")
with st.container(border=True):
    st.markdown('<div class="section-label">The dataset: raw per-node readings</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="section-desc">Every node\'s raw reading feeding one channel\'s fused '
        "verdict &mdash; disclosed, not hidden behind the fused score.</div>",
        unsafe_allow_html=True,
    )
    channel_options = sorted(latest["channel"].unique())
    pick_channel = st.pills("Channel", channel_options, default=channel_options[0], selection_mode="single")
    if pick_channel is None:
        pick_channel = channel_options[0]
    picked = latest[latest["channel"] == pick_channel].iloc[0]
    raw_for_snapshot = raw[
        (raw["day_index"] == picked["day_index"])
        & (raw["hour"] == picked["hour"])
        & (raw["channel"] == pick_channel)
    ].copy()
    raw_for_snapshot["naive_flag"] = (raw_for_snapshot["rssi_dbm"] > ENERGY_DETECTION_THRESHOLD_DBM).astype(int)
    st.dataframe(
        raw_for_snapshot[["node_id", "rssi_dbm", "sensing_confidence", "naive_flag"]].sort_values("node_id"),
        use_container_width=True,
        hide_index=True,
        column_config={
            "node_id": "Node",
            "rssi_dbm": st.column_config.NumberColumn("RSSI", format="%.1f dBm"),
            "sensing_confidence": st.column_config.ProgressColumn("Confidence", min_value=0.0, max_value=1.0, format="%.2f"),
            "naive_flag": st.column_config.CheckboxColumn("Naive: occupied?"),
        },
    )

st.write("")
with st.expander("Audit log (every channel classified, fully explained)"):
    st.dataframe(pd.DataFrame([d.to_dict() for d in decisions]), use_container_width=True, hide_index=True)

with st.expander("Rules layer currently loaded (illustrative placeholder -- see data/DATASET_STATEMENT.md)"):
    st.json(rules)
